// Code generated by go-swagger; DO NOT EDIT.

package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/get-momo/atlar-v1-go-client/client/accounts"
	"github.com/get-momo/atlar-v1-go-client/client/counterparties"
	"github.com/get-momo/atlar-v1-go-client/client/credit_transfers"
	"github.com/get-momo/atlar-v1-go-client/client/direct_debits"
	"github.com/get-momo/atlar-v1-go-client/client/expected_transactions"
	"github.com/get-momo/atlar-v1-go-client/client/external_accounts"
	"github.com/get-momo/atlar-v1-go-client/client/mandates"
	"github.com/get-momo/atlar-v1-go-client/client/third_parties"
	"github.com/get-momo/atlar-v1-go-client/client/transactions"
	"github.com/get-momo/atlar-v1-go-client/client/webhooks"
)

// Default rest HTTP client.
var Default = NewHTTPClient(nil)

const (
	// DefaultHost is the default Host
	// found in Meta (info) section of spec file
	DefaultHost string = "api.atlar.com"
	// DefaultBasePath is the default BasePath
	// found in Meta (info) section of spec file
	DefaultBasePath string = "/"
)

// DefaultSchemes are the default schemes found in Meta (info) section of spec file
var DefaultSchemes = []string{"https"}

// NewHTTPClient creates a new rest HTTP client.
func NewHTTPClient(formats strfmt.Registry) *Rest {
	return NewHTTPClientWithConfig(formats, nil)
}

// NewHTTPClientWithConfig creates a new rest HTTP client,
// using a customizable transport config.
func NewHTTPClientWithConfig(formats strfmt.Registry, cfg *TransportConfig) *Rest {
	// ensure nullable parameters have default
	if cfg == nil {
		cfg = DefaultTransportConfig()
	}

	// create transport and client
	transport := httptransport.New(cfg.Host, cfg.BasePath, cfg.Schemes)
	return New(transport, formats)
}

// New creates a new rest client
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Rest {
	// ensure nullable parameters have default
	if formats == nil {
		formats = strfmt.Default
	}

	cli := new(Rest)
	cli.Transport = transport
	cli.Accounts = accounts.New(transport, formats)
	cli.Counterparties = counterparties.New(transport, formats)
	cli.CreditTransfers = credit_transfers.New(transport, formats)
	cli.DirectDebits = direct_debits.New(transport, formats)
	cli.ExpectedTransactions = expected_transactions.New(transport, formats)
	cli.ExternalAccounts = external_accounts.New(transport, formats)
	cli.Mandates = mandates.New(transport, formats)
	cli.ThirdParties = third_parties.New(transport, formats)
	cli.Transactions = transactions.New(transport, formats)
	cli.Webhooks = webhooks.New(transport, formats)
	return cli
}

// DefaultTransportConfig creates a TransportConfig with the
// default settings taken from the meta section of the spec file.
func DefaultTransportConfig() *TransportConfig {
	return &TransportConfig{
		Host:     DefaultHost,
		BasePath: DefaultBasePath,
		Schemes:  DefaultSchemes,
	}
}

// TransportConfig contains the transport related info,
// found in the meta section of the spec file.
type TransportConfig struct {
	Host     string
	BasePath string
	Schemes  []string
}

// WithHost overrides the default host,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithHost(host string) *TransportConfig {
	cfg.Host = host
	return cfg
}

// WithBasePath overrides the default basePath,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithBasePath(basePath string) *TransportConfig {
	cfg.BasePath = basePath
	return cfg
}

// WithSchemes overrides the default schemes,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithSchemes(schemes []string) *TransportConfig {
	cfg.Schemes = schemes
	return cfg
}

// Rest is a client for rest
type Rest struct {
	Accounts accounts.ClientService

	Counterparties counterparties.ClientService

	CreditTransfers credit_transfers.ClientService

	DirectDebits direct_debits.ClientService

	ExpectedTransactions expected_transactions.ClientService

	ExternalAccounts external_accounts.ClientService

	Mandates mandates.ClientService

	ThirdParties third_parties.ClientService

	Transactions transactions.ClientService

	Webhooks webhooks.ClientService

	Transport runtime.ClientTransport
}

// SetTransport changes the transport on the client and all its subresources
func (c *Rest) SetTransport(transport runtime.ClientTransport) {
	c.Transport = transport
	c.Accounts.SetTransport(transport)
	c.Counterparties.SetTransport(transport)
	c.CreditTransfers.SetTransport(transport)
	c.DirectDebits.SetTransport(transport)
	c.ExpectedTransactions.SetTransport(transport)
	c.ExternalAccounts.SetTransport(transport)
	c.Mandates.SetTransport(transport)
	c.ThirdParties.SetTransport(transport)
	c.Transactions.SetTransport(transport)
	c.Webhooks.SetTransport(transport)
}
