// Code generated by go-swagger; DO NOT EDIT.

package third_parties

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetV1betaThirdPartiesParams creates a new GetV1betaThirdPartiesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetV1betaThirdPartiesParams() *GetV1betaThirdPartiesParams {
	return &GetV1betaThirdPartiesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetV1betaThirdPartiesParamsWithTimeout creates a new GetV1betaThirdPartiesParams object
// with the ability to set a timeout on a request.
func NewGetV1betaThirdPartiesParamsWithTimeout(timeout time.Duration) *GetV1betaThirdPartiesParams {
	return &GetV1betaThirdPartiesParams{
		timeout: timeout,
	}
}

// NewGetV1betaThirdPartiesParamsWithContext creates a new GetV1betaThirdPartiesParams object
// with the ability to set a context for a request.
func NewGetV1betaThirdPartiesParamsWithContext(ctx context.Context) *GetV1betaThirdPartiesParams {
	return &GetV1betaThirdPartiesParams{
		Context: ctx,
	}
}

// NewGetV1betaThirdPartiesParamsWithHTTPClient creates a new GetV1betaThirdPartiesParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetV1betaThirdPartiesParamsWithHTTPClient(client *http.Client) *GetV1betaThirdPartiesParams {
	return &GetV1betaThirdPartiesParams{
		HTTPClient: client,
	}
}

/*
GetV1betaThirdPartiesParams contains all the parameters to send to the API endpoint

	for the get v1beta third parties operation.

	Typically these are written to a http.Request.
*/
type GetV1betaThirdPartiesParams struct {

	/* Limit.

	   Limit resulting response list.Value must be between 1 and 500 (higher values will be coerced down to 500). Defaults to 100.
	*/
	Limit *int64

	/* Token.

	   If response comes back and `nextToken` is populated, use that value in this `token` query to continue pagination.
	*/
	Token *string

	/* Type.

	   Filters out third parties with the given type.
	*/
	Type *string

	/* VendorID.

	   Filters out third parties with the given vendorId.
	*/
	VendorID *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get v1beta third parties params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetV1betaThirdPartiesParams) WithDefaults() *GetV1betaThirdPartiesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get v1beta third parties params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetV1betaThirdPartiesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get v1beta third parties params
func (o *GetV1betaThirdPartiesParams) WithTimeout(timeout time.Duration) *GetV1betaThirdPartiesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get v1beta third parties params
func (o *GetV1betaThirdPartiesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get v1beta third parties params
func (o *GetV1betaThirdPartiesParams) WithContext(ctx context.Context) *GetV1betaThirdPartiesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get v1beta third parties params
func (o *GetV1betaThirdPartiesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get v1beta third parties params
func (o *GetV1betaThirdPartiesParams) WithHTTPClient(client *http.Client) *GetV1betaThirdPartiesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get v1beta third parties params
func (o *GetV1betaThirdPartiesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithLimit adds the limit to the get v1beta third parties params
func (o *GetV1betaThirdPartiesParams) WithLimit(limit *int64) *GetV1betaThirdPartiesParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the get v1beta third parties params
func (o *GetV1betaThirdPartiesParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WithToken adds the token to the get v1beta third parties params
func (o *GetV1betaThirdPartiesParams) WithToken(token *string) *GetV1betaThirdPartiesParams {
	o.SetToken(token)
	return o
}

// SetToken adds the token to the get v1beta third parties params
func (o *GetV1betaThirdPartiesParams) SetToken(token *string) {
	o.Token = token
}

// WithType adds the typeVar to the get v1beta third parties params
func (o *GetV1betaThirdPartiesParams) WithType(typeVar *string) *GetV1betaThirdPartiesParams {
	o.SetType(typeVar)
	return o
}

// SetType adds the type to the get v1beta third parties params
func (o *GetV1betaThirdPartiesParams) SetType(typeVar *string) {
	o.Type = typeVar
}

// WithVendorID adds the vendorID to the get v1beta third parties params
func (o *GetV1betaThirdPartiesParams) WithVendorID(vendorID *string) *GetV1betaThirdPartiesParams {
	o.SetVendorID(vendorID)
	return o
}

// SetVendorID adds the vendorId to the get v1beta third parties params
func (o *GetV1betaThirdPartiesParams) SetVendorID(vendorID *string) {
	o.VendorID = vendorID
}

// WriteToRequest writes these params to a swagger request
func (o *GetV1betaThirdPartiesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Limit != nil {

		// query param limit
		var qrLimit int64

		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt64(qrLimit)
		if qLimit != "" {

			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}
	}

	if o.Token != nil {

		// query param token
		var qrToken string

		if o.Token != nil {
			qrToken = *o.Token
		}
		qToken := qrToken
		if qToken != "" {

			if err := r.SetQueryParam("token", qToken); err != nil {
				return err
			}
		}
	}

	if o.Type != nil {

		// query param type
		var qrType string

		if o.Type != nil {
			qrType = *o.Type
		}
		qType := qrType
		if qType != "" {

			if err := r.SetQueryParam("type", qType); err != nil {
				return err
			}
		}
	}

	if o.VendorID != nil {

		// query param vendorId
		var qrVendorID string

		if o.VendorID != nil {
			qrVendorID = *o.VendorID
		}
		qVendorID := qrVendorID
		if qVendorID != "" {

			if err := r.SetQueryParam("vendorId", qVendorID); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
