// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Limitations limitations
//
// swagger:model Limitations
type Limitations struct {

	// currencies
	Currencies []string `json:"currencies"`

	// identifier types
	IdentifierTypes []string `json:"identifierTypes"`

	// markets
	Markets []string `json:"markets"`
}

// Validate validates this limitations
func (m *Limitations) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this limitations based on context it is used
func (m *Limitations) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Limitations) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Limitations) UnmarshalBinary(b []byte) error {
	var res Limitations
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
