// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// TestbankNationalIdentifier testbank national identifier
//
// swagger:model testbank.NationalIdentifier
type TestbankNationalIdentifier struct {

	// ISO3166 Alpha2 country code
	Market string `json:"market,omitempty"`

	// The identifier itself.
	Number string `json:"number,omitempty"`

	// Type of the national identifier.
	Type string `json:"type,omitempty"`
}

// Validate validates this testbank national identifier
func (m *TestbankNationalIdentifier) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this testbank national identifier based on context it is used
func (m *TestbankNationalIdentifier) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TestbankNationalIdentifier) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TestbankNationalIdentifier) UnmarshalBinary(b []byte) error {
	var res TestbankNationalIdentifier
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
