// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// TestbankBankSlim testbank bank slim
//
// swagger:model testbank.BankSlim
type TestbankBankSlim struct {

	// The BIC code of the bank for the account. Always formatted as 11 characters, if your BIC is only 8 chars, add "XXX" as the last 3 characters.
	Bic string `json:"bic,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// name
	Name string `json:"name,omitempty"`
}

// Validate validates this testbank bank slim
func (m *TestbankBankSlim) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this testbank bank slim based on context it is used
func (m *TestbankBankSlim) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TestbankBankSlim) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TestbankBankSlim) UnmarshalBinary(b []byte) error {
	var res TestbankBankSlim
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
