// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ValidationRule A validation rule applies rules to the affected resource.
//
// swagger:model ValidationRule
type ValidationRule struct {

	// affected resource
	// Example: direct_debits
	AffectedResource string `json:"affectedResource,omitempty"`

	// allowed values
	// Example: ["value1","value2","value3"]
	AllowedValues []string `json:"allowedValues"`

	// required
	// Example: true
	Required bool `json:"required,omitempty"`
}

// Validate validates this validation rule
func (m *ValidationRule) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this validation rule based on context it is used
func (m *ValidationRule) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ValidationRule) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ValidationRule) UnmarshalBinary(b []byte) error {
	var res ValidationRule
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
